go lanuage update

diff --git a/.github/workflows/payment.yml b/.github/workflows/payment.yml
--- a/.github/workflows/payment.yml
+++ b/.github/workflows/payment.yml
@@ -126,105 +126,105 @@ jobs:
             -Dsonar.branch.name=${{ github.ref_name }}
             -Dsonar.qualitygate.wait=true #For quality gate
 
-  #     # -----------------------------
-  #     # Configure AWS Credentials
-  #     # -----------------------------     
-  #     - name: Configure AWS Credentials
-  #       uses: aws-actions/configure-aws-credentials@v4
-  #       with:
-  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  #         aws-region: ${{ inputs.REGION || 'ap-south-1' }}
+      # -----------------------------
+      # Configure AWS Credentials
+      # -----------------------------     
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ inputs.REGION || 'ap-south-1' }}
 
-  #     # -----------------------------
-  #     # Login to Amazon ECR
-  #     # -----------------------------
-  #     - name: Login to Amazon ECR
-  #       id: login-ecr
-  #       uses: aws-actions/amazon-ecr-login@v2 
+      # -----------------------------
+      # Login to Amazon ECR
+      # -----------------------------
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v2 
 
-  #     # -----------------------------
-  #     # Build & Push Docker Image
-  #     # ----------------------------- 
-  #     - name: Build and Push Docker Image
-  #       env:
-  #         ECR_REGISTRY: ${{ inputs.ECRURL || '081654307023.dkr.ecr.ap-south-1.amazonaws.com' }}
-  #         REPOSITORY: ${{ inputs.APPREPO || 'wezvatechfrontend' }}
-  #         IMAGE_TAG: fb${{ github.run_number }}
-  #       run: |
-  #         echo "Building Docker Image..."
-  #         docker build -t $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG .
-  #         echo "Pushing Docker Image..."
-  #         docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
+      # -----------------------------
+      # Build & Push Docker Image
+      # ----------------------------- 
+      - name: Build and Push Docker Image
+        env:
+          ECR_REGISTRY: ${{ inputs.ECRURL || '081654307023.dkr.ecr.ap-south-1.amazonaws.com' }}
+          REPOSITORY: ${{ inputs.APPREPO || 'payment' }}
+          IMAGE_TAG: fb${{ github.run_number }}
+        run: |
+          echo "Building Docker Image..."
+          docker build -t $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG .
+          echo "Pushing Docker Image..."
+          docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
         
-  #     # ------------------------
-  #     # Wait till scan complete
-  #     # ------------------------
-  #     - name: Wait for Scan Completion
-  #       run: |
-  #         for i in {1..12}; do
-  #           STATUS=$(aws ecr describe-image-scan-findings \
-  #             --repository-name ${{ inputs.APPREPO || 'wezvatechfrontend' }} \
-  #             --image-id imageTag=fb${{ github.run_number }} \
-  #             --query 'imageScanStatus.status' \
-  #             --output text 2>/dev/null || echo "NOT_FOUND")
+      # ------------------------
+      # Wait till scan complete
+      # ------------------------
+      - name: Wait for Scan Completion
+        run: |
+          for i in {1..12}; do
+            STATUS=$(aws ecr describe-image-scan-findings \
+              --repository-name ${{ inputs.APPREPO || 'payment' }} \
+              --image-id imageTag=fb${{ github.run_number }} \
+              --query 'imageScanStatus.status' \
+              --output text 2>/dev/null || echo "NOT_FOUND")
 
-  #           echo "Scan Status: $STATUS"
+            echo "Scan Status: $STATUS"
 
-  #           if [ "$STATUS" = "COMPLETE" ]; then
-  #             break
-  #           fi
+            if [ "$STATUS" = "COMPLETE" ]; then
+              break
+            fi
 
-  #           if [ "$STATUS" = "FAILED" ]; then
-  #             echo "Scan failed"
-  #             exit 1
-  #           fi
+            if [ "$STATUS" = "FAILED" ]; then
+              echo "Scan failed"
+              exit 1
+            fi
 
-  #           if [ "$STATUS" = "NOT_FOUND" ]; then
-  #             echo "Scan not yet available, retrying..."
-  #           fi
+            if [ "$STATUS" = "NOT_FOUND" ]; then
+              echo "Scan not yet available, retrying..."
+            fi
 
-  #           sleep 10
-  #         done
+            sleep 10
+          done
 
-  #     # ------------------------
-  #     # Get vulnerability details
-  #     # ------------------------
-  #     - name: Get Vulnerability Counts
-  #       id: scan
-  #       run: |
-  #         CRITICAL=$(aws ecr describe-image-scan-findings \
-  #           --repository-name ${{ inputs.APPREPO || 'wezvatechfrontend' }} \
-  #           --image-id imageTag=fb${{ github.run_number }} \
-  #           --query 'imageScanFindings.findingSeverityCounts.CRITICAL' \
-  #           --output text 2>/dev/null || echo 0)
+      # ------------------------
+      # Get vulnerability details
+      # ------------------------
+      - name: Get Vulnerability Counts
+        id: scan
+        run: |
+          CRITICAL=$(aws ecr describe-image-scan-findings \
+            --repository-name ${{ inputs.APPREPO || 'wezvatechfrontend' }} \
+            --image-id imageTag=fb${{ github.run_number }} \
+            --query 'imageScanFindings.findingSeverityCounts.CRITICAL' \
+            --output text 2>/dev/null || echo 0)
 
-  #         HIGH=$(aws ecr describe-image-scan-findings \
-  #           --repository-name ${{ inputs.APPREPO || 'wezvatechfrontend' }} \
-  #           --image-id imageTag=fb${{ github.run_number }} \
-  #           --query 'imageScanFindings.findingSeverityCounts.HIGH' \
-  #           --output text 2>/dev/null || echo 0)
+          HIGH=$(aws ecr describe-image-scan-findings \
+            --repository-name ${{ inputs.APPREPO || 'wezvatechfrontend' }} \
+            --image-id imageTag=fb${{ github.run_number }} \
+            --query 'imageScanFindings.findingSeverityCounts.HIGH' \
+            --output text 2>/dev/null || echo 0)
 
-  #         echo "Critical: $CRITICAL"
-  #         echo "High: $HIGH"
+          echo "Critical: $CRITICAL"
+          echo "High: $HIGH"
 
-  #         echo "critical=$CRITICAL" >> $GITHUB_OUTPUT
-  #         echo "high=$HIGH" >> $GITHUB_OUTPUT   
+          echo "critical=$CRITICAL" >> $GITHUB_OUTPUT
+          echo "high=$HIGH" >> $GITHUB_OUTPUT   
           
-  #     # -----------------------
-  #     # Quality Gate for Image
-  #     # ----------------------   
-  #     - name: Enforce Security Gate (Ignore Failures)
-  #       run: |
-  #         CRITICAL=${{ steps.scan.outputs.critical }}
-  #         HIGH=${{ steps.scan.outputs.high }}
+      # -----------------------
+      # Quality Gate for Image
+      # ----------------------   
+      - name: Enforce Security Gate (Ignore Failures)
+        run: |
+          CRITICAL=${{ steps.scan.outputs.critical }}
+          HIGH=${{ steps.scan.outputs.high }}
 
-  #         if [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ]; then
-  #           echo "⚠️ Vulnerabilities found but ignored"
-  #           exit 1
-  #         else
-  #           echo "✅ No vulnerabilities"
-  #         fi
+          if [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ]; then
+            echo "⚠️ Vulnerabilities found but ignored"
+            exit 1
+          else
+            echo "✅ No vulnerabilities"
+          fi
 
   # # -----------------------------
   # # Trigger CD Job
